### ISSUE TITLE
Library does not appear to work

### ISSUE THREAD

**Issue by PendletonJones** [iameli/kubernetes-letsencrypt#1]
=================================================
kubernetes-letsencrypt: Generating secret
=================================================

Done!
Error from server: secrets "letsencrypt-ssl" not found

=================================================
kubernetes-letsencrypt: Secret does not exist, running kubectl create
=================================================

error validating "newsecret.yml": error validating data: unexpected type: object; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by iameli** [comment]
Hm. What version of Kubernetes are you using?

**Comment by iameli** [comment]
Fixed here, looks like it just needed a version bump. https://github.com/iameli/kubernetes-letsencrypt/commit/6bb29c7f8f2095e801728ef60a9b9849efd10bad
